### ISSUE TITLE
How to add "Choose file for Image" and "print HEX value" in  class="swatch" div

### ISSUE THREAD

**Issue by keshavnaidu** [lokesh/color-thief#130]
Hi Lokesh,
Your app is excellent. 

Can you help me out for adding a HEX values instead of RGB in class="swatch" .
Also a Choose file instead of Drag and drop.
I would like to credit & contribute u to using "color thief" for my site.

Thanks & Regards.

**Comment by AlfredJKwack** [comment]
Hi,

You can easily write your own routing to convert RGB to HEX. Converting the array returned by color-thief should be no more effort.

To get you started and pointed in the right direction:
```

function componentToHex(c) {
    var hex = c.toString(16);
    return hex.length == 1 ? "0" + hex : hex;
}
function rgbToHex(r, g, b) {
    return "#" + componentToHex(r) + componentToHex(g) + componentToHex(b);
}
alert( rgbToHex(0, 51, 255) ); // #0033ff
```

As for the choose file, instead of drag and drop... well. I'd hate to troll you so I'll leave it at that.

**Comment by lokesh** [comment]
Move instructions on rgb to hex conversion on to the demo site in a new FAQ section:
https://lokeshdhakar.com/projects/color-thief/#faq

**Comment by lokesh** [comment]
Thanks. Added a FAQ section that includes the rgb to hex conversion code:
https://lokeshdhakar.com/projects/color-thief/#faq

**Comment by SasoriDevelopment** [comment]
Is it possible to get RGBA-Values instead of RGB-Values?
