### ISSUE TITLE
[Suggestion] A way to exclude colors like Skin?

### ISSUE THREAD

**Issue by WebAlvo** [lokesh/color-thief#133]
Hi, I love your project, I'm using on a website, it's very cool, the only problem is that website is to upload shoes photos, and most is being used by someone.

There is anyway to exclude colors? like skin most common or something like that?

**Comment by AlfredJKwack** [comment]
Sure there is.  Here's one way to approach the problem: 

There is no way to explicitly exclude colors up front by supplying an array of colors that should be ignored. You will have to deal with this once you have a palette returned. So if you want 10 colors in the palette and typically 4 of these are skin colors you will need to have a palette of 14 so that you still get 10 after you remove the skin colors. Do note that this assumes you have a representative sample of images that you can analyse to make that determination (and can accept some variance), or you have another way to work around this.

Now, how do you know what colors to exclude? To that end you will have to produce an array of _all_ the RGB values you consider "skin color". 

One way to go about that is to take some assumptions. First let us assume your models are caucasian. There are a couple of [predefined palette colors](https://www.color-hex.com/color-palette/737) for that. A couple of searches should give you a pretty decent list of things to work from.

Unfortunately they do not list _all_ the rgb values between any 2 colors in the palette. To get that you will need to use some tooling. Something like [gradstop](https://github.com/Siddharth11/gradstop) will spit out all the gradient stops between two (or more) colors. Just make sure you feed a large number of stops between any two given colors so you catch every rgb value. You will want to capture all of that output in an array and save it somewhere. Remember that you want to do that for every pair of colors in the palette; that would be 10 pairs to run if your palette contains 5 colors.

Now that you have a complete list of all "skin" colors and you have the output from color-thief all you need to do is filter out the skin colors from the result. 

Bear in mind that the skin color may be the dominant color though!

**Comment by lokesh** [comment]
Closing out older issues.This feature is not on the roadmap, but do take a look at @AlfredJKwack's excellent comment.
