### ISSUE TITLE
Areas sampling

### ISSUE THREAD

**Issue by thom4parisot** [lokesh/color-thief#17]
Hello :-)

Great tool! I wondered how complex it would be to split the results for different areas.
For example, I'd like to sample only 1/3 in height of an image. to sample the sky colours.

Something like this API:

``` javascript
var colors = new ColorThief({
  areas: {
    sky: [0, 100%, 33%, 100%],
    ground: [33%, 100%, 66%, 100%]
  }
});

console.log(colours.getPalette(img, 8);
/*
returns {
  sky: [ [num, num, num], [num, num, num], ... ],
  ground: [ [num, num, num], [num, num, num], ... ]
}
*/
```

**Comment by elliottregan** [comment]
Any thoughts on how to do this? I'm using this to set the text color of a site header, based on how dark/light the image is. It works most of the time, but some images that are mostly light-colored, with a bit of dark where the header actually goes don't work.

**Comment by Pluto1010** [comment]
You could just extract the border areas around the image from the source image and provide this to ColorThief instead of the whole image. This would give you palette's for specific area. Any other area should also be possible. Just provide this area to ColorThief. It should not require much code to do this.
