### ISSUE TITLE
ColorThied don't working on IE 11

### ISSUE THREAD

**Issue by TonyHuynh68** [lokesh/color-thief#87]
I open demo ColorThief in IE 11 and drap svg image to "Try It Yourself" box and IE have error in colorThief.getColor(sourceImage); -> IndexSizeError

**Comment by lokesh** [comment]
This looks to be an issue with the Color Thief page's drag'n'drop demo and not the script itself. The problem is likely related to the way IE behaves after a canvas has svg data drawn on it. You can read more about it here:
https://connect.microsoft.com/IE/feedback/details/828416/cavas-todataurl-method-doesnt-work-after-draw-svg-file-to-canvas
